services:
  p2:
    build:
      context: .
      dockerfile: Dockerfile
    image: novocert-p2-1:compose-build
    platform: linux/amd64
    container_name: novocert-p2-1
    # user: "${UID:-1000}:${GID:-1000}"
    volumes:
      # Output directory
      - type: bind
        source: ./test_data/output
        target: /app/output/
